### ISSUE TITLE
make it a template repository

### ISSUE THREAD

**Issue by riezebosch** [proscrumdev/battleship-java#18]
to make it easy to set up repositories on GitHub for the respective teams.

docs: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

Found out you can only have 1 fork of a given repository in your organization.
You don't need nor want the fork functionality since you're not accepting PRs from students
you don't need the original history for the students to be available.

**Comment by tschissler** [comment]
Done for all repositories
